version: "2"
services:
  incoders_php:
    container_name: incoders_php
    build:
        context: ./build/php
        dockerfile: Dockerfile
    image: iago/incoders:php7.3
    ports:
        - "8050:8050"
    volumes:
        - '../App/incoders:/var/www/html/incoders'